### PR TITLE
Glen

### PR DESCRIPTION
**Pull request by glennfor**
I realised I made a big change and didn't submit a PR. I remeber telling you I refactored the game process into its own class that can manage the state and the game loop so we wont have to use global variables... Anyways. Review and let me know

### CODE REVIEW

**Comment by JosiasAurel** [comment]
It looks like the game leaks memory __A LOT__ faster than I could realise. Saying because after building the game it slows down at a seemingly exponential rate until my computer is unresponsive. 
Dunno if you tried building.

**Comment by JosiasAurel** [comment]
Also please build and test your changes before pushing :-/

**Comment by glennfor** [comment]
I did test. If it doesn't work, then it may be an oversight from committing after some minor changes before the PR

**Comment by JosiasAurel** [comment]
> I did test. If it doesn't work, then it may be an oversight from committing after some minor changes before the PR

okay. It will build if you prepend the `const` before the sprite maps

**Comment by glennfor** [comment]
I have resolved the conflicts by making compromises on both of our code. I did keep everything you added but I also kept the code for the Chess class. The whole thing is basically broken now so I will update myself and fix the petty errors before we carry on

**Comment by JosiasAurel** [comment]
kk

**Pull request merged**
